name: CI - File health

on: [pull_request, push]

jobs:
  ci:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install tools
        uses: actions/setup-python@v4
        with:
          python-version: '*'

      - name: Check files
        uses: pre-commit/action@v3.0.0
